"""Add is_draft field

Revision ID: 78546d4888e6
Revises: ab358b412419
Create Date: 2026-05-18 11:58:15.129711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78546d4888e6'
down_revision = 'ab358b412419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
