"""Add segment, line, and style

Revision ID: 87c83114edb9
Revises: 78546d4888e6
Create Date: 2026-05-20 11:51:33.545055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c83114edb9'
down_revision = '78546d4888e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('styles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.alter_column('price_list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('line_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('style_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'segments', ['segment_id'], ['id'])
        batch_op.create_foreign_key(None, 'lines', ['line_id'], ['id'])
        batch_op.create_foreign_key(None, 'styles', ['style_id'], ['id'])
        batch_op.drop_column('type')
        batch_op.drop_column('segment')
        batch_op.drop_column('line')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('segment', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('style_id')
        batch_op.drop_column('line_id')
        batch_op.drop_column('segment_id')

    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('product_variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price_list_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('styles')
    op.drop_table('segments')
    op.drop_table('lines')
    # ### end Alembic commands ###
